### ISSUE TITLE
Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by creaz35** [redotvideo/examples#20]
Hi Guys,

After using npm run render, i'm getting the following:

```
> tsc && node dist/render.js

Rendering video...
Worker 0: JSHandle:finished downloading
Render progress, worker 0: 1% 
Render progress, worker 0: 4% 
Render progress, worker 0: 12% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 20% 
Render progress, worker 0: 26% 
Render progress, worker 0: 35% 
Render progress, worker 0: 39% 
Render progress, worker 0: 39% 
Render progress, worker 0: 39% 
Render progress, worker 0: 43% 
Render progress, worker 0: 51% 
Render progress, worker 0: 58% 
Render progress, worker 0: 59% 
Render progress, worker 0: 59% 
Render progress, worker 0: 59% 
Render progress, worker 0: 64% 
Render progress, worker 0: 72% 
Render progress, worker 0: 79% 
Render progress, worker 0: 79% 
Render progress, worker 0: 79% 
Render progress, worker 0: 80% 
Render progress, worker 0: 87% 
Render progress, worker 0: 94% 
Render progress, worker 0: 100% 
Error: Error: ffmpeg exited with code 1: Output #0, mp4, to 'output\video-visuals.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (C:\Users\Brian\Desktop\projects\testvideo\ok\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ffmpeg exited with code 1: Output #0, mp4, to 'output\video-visuals.mp4':
Output file #0 does not contain any stream

    at ChildProcess.<anonymous> (C:\Users\Brian\Desktop\projects\testvideo\ok\node_modules\fluent-ffmpeg\lib\processor.js:180:22)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v21.6.0
```

The video gets saved but no images or text, only audio playing. 

Thanks for the help!

**Comment by hoangquocvietbro** [comment]
Did you fix this error?

**Comment by devvMuhammad** [comment]
Did you fix this error?
