### ISSUE TITLE
400/401 error in youtube shorts example

### ISSUE THREAD

**Issue by K-Jadeja** [redotvideo/examples#9]
`npm start` runs fine and I can edit the demo video too
`npm run render` does not generate a file and instead prints out a lengthy message containing calls to 11labs with 400/401 errors

All my API keys are corrects and the script is getting generated too. The problem occurs at the 11labs part of the process.

Can you please confirm if the code is up to date?

**Comment by justusmattern27** [comment]
@K-Jadeja Hi, can you please share the error messages from Eleven labs with me? The code should be up to date

**Comment by K-Jadeja** [comment]
Hey @justusmattern27, I found out that the error message was contained within a Buffer object in the data field of the response
```
 data: Buffer(476) [Uint8Array] [
      123,  34, 100, 101, 116,  97, 105, 108,  34,  58, 123,  34,
      115, 116,  97, 116, 117, 115,  34,  58,  34, 100, 101, 116,
      101,  99, 116, 101, 100,  95, 117, 110, 117, 115, 117,  97,
      108,  95,  97,  99, 116, 105, 118, 105, 116, 121,  34,  44,
       34, 109, 101, 115, 115,  97, 103, 101,  34,  58,  34,  85,
      110, 117, 115, 117,  97, 108,  32,  97,  99, 116, 105, 118,
      105, 116, 121,  32, 100, 101, 116, 101,  99, 116, 101, 100,
       46,  32,  70, 114, 101, 101,  32,  84, 105, 101, 114,  32,
      117, 115,  97, 103,
      ... 376 more items
    ]
```
which translates to 
```
{
  "detail": {
    "status": "detected_unusual_activity",
    "message": "Unusual activity detected. Free Tier usage limit has been reached. Please upgrade your account to continue using the API."
  }
}
```
Apparently, I had more than one free accounts on my IP address :(   
Will try to replace elevenlabs with some other good tts - Do you have any suggestions? 

The error I am stuck at now is this:
```
PS C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts> npm run render

> revideo@0.0.0 render
> tsc && node dist/render.js

Generating assets...
script Did you know that the moon landing was not a hoax? Astronauts Neil Armstrong and Buzz Aldrin made history in 1969.
Generating images...
Assets generated! Rendering video...
C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\LifecycleWatcher.js:100
            this.#terminationDeferred.resolve(new Error('Navigating frame was detached'));
                                              ^

Error: Navigating frame was detached
    at #onFrameDetached (C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\LifecycleWatcher.js:100:47)
    at C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\third_party\mitt\mitt.js:62:7    
    at Array.map (<anonymous>)
    at Object.emit (C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\third_party\mitt\mitt.js:61:20)
    at CdpFrame.emit (C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\puppeteer\common\EventEmitter.js:83:23)
    at #removeFramesRecursively (C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\FrameManager.js:450:15)
    at #onClientDisconnect (C:\Users\Krishna\Desktop\Workspace\Github-Projects\revideo\youtube-shorts\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\FrameManager.js:94:42)

Node.js v20.15.0
```
I tried updating puppeteer packages but still getting this.
Thanks for the help!
